---
image: voegelas/debian-devel

test:
  stage: test
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always
  script:
    - perl Makefile.PL
    - cover -test
    - sudo make install
    - cpanm --test-only IP::Geolocation::MMDB
