---
name: linux

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  perl:

    runs-on: ubuntu-latest

    container:
      image: voegelas/debian-devel

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          cpanm --quiet --notest --installdeps .
      - name: Run tests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: |
          perl Makefile.PL
          cover -test -report coveralls
      - name: Test IP::Geolocation::MMDB
        run: |
          sudo make install
          cpanm IP::Geolocation::MMDB
